name: Documentation

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  workflow_call:

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Package
        shell: bash
        run: |
          pip install .
          pushd doc; make install-filters; popd

      - name: Build docs
        shell: bash
        run: |
          pushd doc; make doc; popd

      - name: Environment Information
        shell: bash
        run: |
          ls -la doc
          ls -la doc/reference

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_site
