name: Documentation

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  workflow_call:

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Package and Doc Dependencies
        run: |
          uv pip install "."
          make -C doc install-all

      - name: Build Documentation
        run: make -C doc doc

      - name: Environment Information
        run: |
          ls -la doc
          ls -la doc/reference

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_site
