name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]*'
  pull_request:
  workflow_call:

jobs:
  unittests:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: ["3.11", "3.13"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Package and Doc Dependencies
        run: |
          uv pip install ".[build,test]"
          make -C doc install-all

      - name: Run Tests
        run: make test
